[package]
name = "vodnik-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
num-traits = { workspace = true }
rkyv ={ workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
